# Generated by Django 4.2.3 on 2023-10-14 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Teacher_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_superuser': True, 'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='attender', to=settings.AUTH_USER_MODEL),
        ),
    ]
