# Generated by Django 4.2.3 on 2023-10-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher_App', '0005_alter_attendance_attender'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
