# Generated by Django 4.2.3 on 2023-10-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher_App', '0006_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
    ]
