# Generated by Django 4.2.3 on 2023-10-16 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher_App', '0007_attendance_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='timeSession',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Teacher_App.timesession'),
        ),
    ]
