# Generated by Django 4.2.3 on 2023-10-26 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher_App', '0010_alter_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='timeSession',
            new_name='timesession',
        ),
    ]
