# Generated by Django 4.2.3 on 2023-11-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher_App', '0014_alter_studymaterial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
