# Generated by Django 4.2.3 on 2023-09-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_App', '0003_user_date_of_birth_user_gender_user_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
